quiz_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rainfall/', include('rainfall_record.urls', namespace="rainfall")),
]

rainfall_record/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='homepage'),
    url(r'^records/$', views.get_details, name='records'),
    url(r'^graph_detail/$', views.get_records, name='graph'),
    url(r'^show_graph/(?P<year>[0-9]{4})/$', views.display_graph, name='show_graph'),
]

rainfall_record/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.core.validators import MinValueValidator
# Create your models here.
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from datetime import date


def validate_date(value):
    date_today = date.today()
    if value > date_today:
        raise ValidationError(
            _('%(value)s is invalid. You can not set date in the future.'),
            params={'value': value},
        )


@python_2_unicode_compatible
class Region(models.Model):
    region_name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return str(self.region_name)


@python_2_unicode_compatible
class Rainfall(models.Model):
    region = models.ForeignKey(Region)
    amount = models.DecimalField(
        max_digits=5,
        decimal_places=1,
        default=0.0,
        validators=[MinValueValidator(0.0)])
    date = models.DateField(validators=[validate_date])

    def __str__(self):
        return str(self.region) + "-" + str(self.date)

rainfall_record/forms.py
from .models import Rainfall, Region
from django import forms
from django.core.validators import MinValueValidator
import datetime


class RainfallForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        # Class inheritance is to allow choices of region field to
        # be obtained from queryset of Region model
        super(RainfallForm, self).__init__(*args, **kwargs)
        # region field that uses data from Region model
        region = forms.ChoiceField(
            choices=Region.objects.all(),
            widget=forms.Select,
            required=True)

    # Amount field that gets decimal values of rainfall
    # can't benegative value
    amount = forms.DecimalField(
        max_digits=5,
        decimal_places=1,
        validators=[MinValueValidator(0.0)],
        required=True)

    # Date the record was taken, can't be greater than the current date
    date = forms.DateField(
        widget=forms.SelectDateWidget())

    class Meta:
        model = Rainfall
        fields = ['region', 'amount', 'date']


class RecordForm(forms.Form):
    min_year = 2000  # Sets the lowest year that can be selected
    current_year = datetime.date.today().year  # Gets the current year
    # Validates if current year selected is greater than minimun set
    if min_year < current_year:
        # Sets the choices starting with the current year
        # and decreases to the minimum
        years = [(x, x) for x in range(current_year, min_year, -1)]
    else:
        years = []

    year_choices = forms.ChoiceField(
        choices=years,
        widget=forms.Select,
        required=True)

rainfall_record/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import RainfallForm, RecordForm
from .models import Region, Rainfall
from django.core.urlresolvers import reverse
from django.db.models import Sum
from matplotlib import pylab
from pylab import *
import PIL.Image

from django.http import HttpResponse
# Create your views here.


# View for homepage
def home(request):
    return render(request, 'rainfall_record/homepage.html', {})


# View for displayig graph, uses matplotlib to generate graph
# and pillow to display it using httpresponse
def display_graph(request, year):
    regions_object = Region.objects.all()  # region_objects
    amount_total = []  # List for storing sum ofamount in a region
    region_names = []  # List for storing region names
    for region in regions_object:
        region_names.append(region.region_name)
        # Filters Rainfall object by region and by year
        rainfall_data = Rainfall.objects.filter(
            date__year=year).filter(
            region=region)
        # If rainfall data is not empty, sum the amount
        if len(rainfall_data) > 0:
            amount_total.append(
                float(rainfall_data.aggregate(Sum('amount'))['amount__sum']))
        # Otherwise set to 0
        else:
            amount_total.append(0)

    # Generate bar graph using data obtained from
    # database using matplotlib
    y_pos = np.arange(len(region_names))
    plt.bar(y_pos, amount_total, align='center', alpha=0.5)
    plt.xticks(y_pos, region_names)
    plt.ylabel('Amount (mm)')
    plt.title('Regions')
    grid(True)

    # Converts bar graph into image using Pil
    canvas = pylab.get_current_fig_manager().canvas
    canvas.draw()
    graphIMG = PIL.Image.frombytes(
        "RGB",
        canvas.get_width_height(),
        canvas.tostring_rgb())

    pylab.close()
    response = HttpResponse(content_type="image/png")
    graphIMG.save(response, "PNG")

    # Returns image as HttpResponse
    return response


# View for display form to input rainfall data
def get_details(request):
    if request.method == 'POST':
        form = RainfallForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('rainfall:homepage'))
    else:
        form = RainfallForm()
    return render(
        request,
        'rainfall_record/rainfall_form.html',
        {'form': form})


# View containg form for selecting year to be
# used in displaying graph
def get_records(request):
    if request.method == 'POST':
        form = RecordForm(request.POST)
        if form.is_valid():
            year_choices = form.cleaned_data['year_choices']
            return HttpResponseRedirect(
                reverse('rainfall:show_graph', args=(year_choices,)))
    else:
        form = RecordForm()
    return render(
        request,
        'rainfall_record/rainfall_chart.html',
        {'form': form})

rainfall_record/templates/base.html
<!DOCTYPE html>

<html>
    <head>
        {% load bootstrap3 %}

        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {% block bootstrap3_content %}
        <div class="container">
            <nav  class="navbar navbar-default">
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    <li><a href="{%url 'rainfall:homepage' %}">Home</a></li>
                    <li><a href="{%url 'rainfall:records' %}">Record data</a></li>
                    <li><a href="{%url 'rainfall:graph' %}">Display graph</a></li>
                </ul>
                </div>
            </nav>
        <title>{% block title %}{% endblock%}</title>

    </head>

    <body>
    {% bootstrap_messages %}
    
    {% block content %}{% endblock%}
    </div>
    {% endblock %}
    </body>
</html>

rainfall_record/templates/rainfall_record/homepage.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
	Homepage
{% endblock %}

{% block content %}
	<ul>
		<li><a href="{%url 'rainfall:records' %}">Add rainfall data</a></li>
		<li><a href="{%url 'rainfall:graph' %}">Plot records in chart</a></li>
	</ul>
{% endblock %}

rainfall_record/templates/rainfall_record/rainfall_chart.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
	Rainfall chart
{% endblock %}

{%block content%}
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<form action="{%url 'rainfall:graph'%}" method="POST" class="form">
		{% csrf_token %}
		{% bootstrap_form form layout='horizontal' %}
	    {% buttons %}
		
		<button type="submit" class="btn btn-primary">
	      {% bootstrap_icon "star" %} Show
	    </button>
	    {% endbuttons %}
	</form>
{% endblock %}

rainfall_record/templates/rainfall_record/rainfall_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
	Rainfall data input
{% endblock %}

{%block content%}
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<form action="{%url 'rainfall:records'%}" method="POST">
		{% csrf_token %}
		{% bootstrap_form form layout='horizontal' %}
	    {% buttons %}
		
		<button type="submit" class="btn btn-primary">
	      {% bootstrap_icon "star" %} Show
	    </button>
	    {% endbuttons %}
	</form>
{% endblock %}